# Generated by Django 6.0.6 on 2026-06-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='hora_retiro',
            field=models.CharField(blank=True, choices=[('09:00-11:00', '09:00 a 11:00'), ('11:00-13:00', '11:00 a 13:00'), ('13:00-15:00', '13:00 a 15:00'), ('15:00-17:00', '15:00 a 17:00'), ('17:00-19:00', '17:00 a 19:00')], max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='modo_pago',
            field=models.CharField(choices=[('online', 'Pagado online (Mercado Pago)'), ('local', 'Pago al retirar')], default='local', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
