# Generated by Django 6.0.6 on 2026-06-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_pedido_hora_retiro_pedido_modo_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='hora_retiro',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
